export const DEFAULT_MARKETS = {
  increment: 0,
  code: '',
  contractaddress: '',
  copies: 0,
  id: '',
  image: '',
  name: '',
  price: 0,
  purchaseAgreement: '',
  saleEndTime: 0,
  saleStartTime: 0,
  soldAmount: 0,
  summary: '',
  saleStatus: '',
  userId: '',
};
